[package]
name = "react-native-fast-markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = "1.0.0-alpha.20"
pulldown-cmark = { version = "0.12.1", features = [
	"simd",
	"html",
], default-features = false }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
